name: Docker Build, Push, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2  
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: ghcr.io/${{ github.repository }}/fastapi-youtube-transcript-api:latest  

      
      - name: Build and Publish API
        run: |
          IMAGE_NAME_LOWER=$(echo ${{ env.API_NAME }} | tr '[:upper:]' '[:lower:]')
          docker build . -f Dockerfile --tag ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER
          docker push ${{ env.REGISTRY }}/$IMAGE_NAME_LOWER
      - name: Run Docker container
        run: docker run --rm ghcr.io/${{ github.repository }}/fastapi-youtube-transcript-api:latest in this do I need use action secrets
