name: Docker Build, Push, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2  
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4  
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: ghcr.io/${{ github.repository }}/fastapi-youtube-transcript-api:latest  

      - name: Publish Docker image
        run: |
         - name: Publish Docker image
  run: |
    ghcr_image="ghcr.io/harshanmathew/youtube/fastapi-youtube-transcript-api:latest"
    echo "Publishing $ghcr_image..."
    curl -X PATCH \
      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      -H "Accept: application/vnd.github.v3+json" \
      https://api.github.com/user/packages/container/ghcr.io/harshanmathew/youtube/fastapi-youtube-transcript-api/versions \
      -d '{"visibility":"public"}'

      - run: |
          docker run -d -p 8000:8000 ghcr.io/${{ github.repository }}/fastapi-youtube-transcript-api:latest
          echo "Container is running on port 8000"
